### ISSUE TITLE
Fix condition for migrate-annotated-servlets recipe

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#141]
**Describe the bug**
The `migrate-annotated-servlets` recipe should only be shown if any class annotated with `@WebServlet` was found.
But currently the condition of the recipe checks for any import starting with `javax.servlet` and therefore the recipe is shown if an application has any import under `javax.servlet`.

**Expected behavior**
The `migrate-annotated-servlets` recipe is only shown as applicable if the scanned application  has an import `javax.servlet.WebServlet` or (even better) has a type annotated with `@SebServlet`.

**Comment by Pawank06** [comment]
Hello ! I am beginner to open source and I'm familiar with java can you please help me how can I solve this issue .

**Comment by fabapp2** [comment]
Hi @Pawank06 

Welcome to SBM 🚀 

This issue requires a change of the [condition](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/61be85e0e6524d2c6988d8f2ca8199ee1947af4c/components/sbm-recipes-jee-to-boot/src/main/resources/recipes/migrate-annotated-servlets.yaml#L6) for the `migrate-annotated -servlets` recipe.
See `HasAnnotation` condition which should do a better job here.
The tests can be added in `MigrateAnnotatedServletRecipeTest` using `TestProjectContext` to build the `ProjectContext` used as a fixture for the test.
Don't hesitate to ask in case you need further help.

**Comment by fabapp2** [comment]
Hi @Pawank06 
Do you want to take this issue? I'd assign you then
