### ISSUE TITLE
3.0.0-M2 Image Banner Support Removed

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#150]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M2-Release-Notes#image-banner-support-removed

### What needs to be done 
If `banner.gif`, `banner.jpg`, or `banner.png` are found warn the user in the report about removed support of images as banner 

- [ ] Check if `banner.gif`, `banner.jpg`, or `banner.png` exist
- [ ] Create report and ask user to replace the banner with a banner.txt file

## Additional Information
See [`DatabaseDriverGaeFinder`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/bc5dc957096c66aef319e142d8d75de50c931e1d/components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade_27_30/checks/DatabaseDriverGaeFinder.java) and [`DatabaseDriverGaeSectionBuilder`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/bc5dc957096c66aef319e142d8d75de50c931e1d/components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade_27_30/checks/DatabaseDriverGaeSectionBuilder.java)

**Comment by sanagaraj-pivotal** [comment]
ready to be picked up, decide what to do.

**Comment by fabapp2** [comment]
To check off M2 changes (this seems to be the last missing) I'd say let's create this report section.

**Comment by fabapp2** [comment]
Enhance recipe to deal with `spring.banner.location=...` property pointing to a non-default location
