### ISSUE TITLE
3.0.0-M1 - Property Replacements

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#151]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M1-Configuration-Changelog

This issue is related to #158 as the removed properties belong to modules which are not supported anymore.

## Removed Properties
- If #158 had no matches (no unsupported modules used) the removed properties can be removed
- If #158 had matches the upgrade fails with a note that unsupported modules are used

### Questions
- What if removed properties were found for modules that are still supported? E.g. `spring.data.elasticsearch.client.reactive.use-ssl`

## Changed Properties
- Replace the old property with the new value

**Comment by sanagaraj-pivotal** [comment]
ready for pickup

**Comment by fabapp2** [comment]
closed in #189
