### ISSUE TITLE
2.7: Properties under spring.security.saml2.relyingparty.registration.{id}.identityprovider have been moved

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#155]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#deprecations-in-spring-boot-27

- [ ] Is this implemented in `rewrite-spring`? If so, where? 
- [ ] Implement a Condition in SBM for this migration
- [ ] How can the rewrite recipe be integrated into an SBM action/recipe that's only applicable if the condition holds true?

**Comment by sanagaraj-pivotal** [comment]
not done, ready for pick up

**Comment by fabapp2** [comment]
closed in PR #189
