### ISSUE TITLE
3.0.0-M1 JSON-B

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#159]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M1-Release-Notes#json-b

### What needs to be done

Dependency management for Apache Johnzon has been removed in favor of Eclipse Yasson. A Jakarta EE 9-compatible version of Apache Johnzon can be used with Spring Boot 3, but you will now have to specify a version in your dependency declaration.

if dependency to Johnzon found on classpath...

1. if the  version is managed by Spring Boot
1.1 replace it with `org.apache.johnzon:johnzon-core:1.2.18:jakarta`
2 if the  version is NOT managed by Spring Boot (declared)
2.1 replace it with `org.apache.johnzon:johnzon-core:1.2.18:jakarta`

- [ ] Implement an Action with the described steps 
- [ ] Write a test using `TestProjectContext` for this Action
- [x] Find out what 'compatible' means, which version of Johnzon is used in Boot 2.7 and for which version of Johnzon a new Jakarta Compatible version exists
- [ ] Implement the replacement

**Comment by ravig-kant** [comment]
Hi @fabapp2 

What is the expected solution for this change? Is SBM suppose to add "Jakarta EE 9-compatible version of Apache Johnzon" in build files?

Ravi

**Comment by fabapp2** [comment]
Hi @ravig-kant,
#158 is another issue that you could pick if you like.

**Comment by ravig-kant** [comment]
Thanks for the explanation @fabapp2. I will work on this one.

**Comment by ravig-kant** [comment]
Hi @fabapp2 

As of today, Apache Johnzon supports JSON-B 1.0 specifications while JakarataEE 9.0 requires JSON-B 2.0. So, shall I raise an exception if the recipe detects an explicit dependency on Apache Johnzon?

Thanks
Ravi

**Comment by fabapp2** [comment]
Hi @ravig-kant 

Thanks for looking into it. I can follow you and can't see which version of Johnzon should be used in place of Yasson.
I will bring it back to the team. 

For reference:
Spring Boot `3.0.0-M3` manages `yasson:2.0.4` ([JEE 9](https://projects.eclipse.org/projects/ee4j.yasson/releases/2.0.0))
Spring `Boot 2.7.x` manages `johnzon:1.2.18` ([JEE 8](https://johnzon.apache.org/download.html))

For now, I think this should become a precondition check in #237. Not sure about your current state but throwing an exception would work for now (and get it merged). As soon as we start working on #237 we can see how to integrate it there?

**Comment by fabapp2** [comment]
Hi @ravig-kant 
The Johnzon replacement for Yasson `2.0.4` is
```
<dependency>
        <groupId>org.apache.johnzon</groupId>
        <artifactId>johnzon-core</artifactId>
        <version>1.2.18</version>
        <classifier>jakarta</classifier>
</dependency>
```

**Comment by ravig-kant** [comment]
Thanks, @fabapp2 

I will start fixing.

**Comment by ravig-kant** [comment]
Hi @fabapp2 

PR raised.

Ravi

**Comment by tkvangorder** [comment]
FYI, we have included a recipe in rewrite-migrate-java to make the appropriate changes to johnzon dependencies in maven:

https://github.com/openrewrite/rewrite-migrate-java/issues/139
