### ISSUE TITLE
3.0.0-M2 Dependency Upgrades

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#167]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M2-Release-Notes#dependency-upgrades

**Comment by ravig-kant** [comment]
Hi @fabapp2 

I would like to pick up this issue. Let me know if there are any other plans.

Thanks
Ravi

**Comment by fabapp2** [comment]
Hi @ravig-kant!
Sorry for the late reply but I've been on PTO.
Thanks for your interest your contributions are more than welcome!

Scanning the section in the release notes I guess we have nothing to do in this issue as the versions will be provided by Boot's dependency management.
Could you try to find another issue catches your interest?

[Here's the backlog](https://github.com/spring-projects-experimental/spring-boot-migrator/projects/1) for the 3.0.0-M3 upgrade. I am working on adding some more information to (some of) these issues at the moment and will order them by priority afterwards.

**Comment by fabapp2** [comment]
Closing this issue as there's nothing to migrate.
