### ISSUE TITLE
3.0.0-M3 Support for Apache Solr Removed

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#226]
Find usages of [`spring-data-solr`](https://spring.io/projects/spring-data-solr) and create report.

See `CommonsMultipartResolverSectionBuilderTest` ff. for example

**Comment by ravig-kant** [comment]
Hi @fabapp2 

Can I work on this issue? Is there any other prereq pending for this work?

**Comment by fabapp2** [comment]
picked by @ravig-kant

**Comment by ravig-kant** [comment]
https://github.com/spring-projects-experimental/spring-boot-migrator/pull/371

**Comment by ravig-kant** [comment]
Hi @fabapp2 

I am facing issue with OpenRewriteType.getExtends() method. I have posted my query inline with your review comment.
