### ISSUE TITLE
3.0.0-M3 `PagingAndSortingRepository` does not extend `CrudRepository` anymore

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#236]
With `spring-data-jpa` `PagingAndSortingRepository` does not extend `CrudRepository` anymore.

- [ ] Find all classes/interfaces that extends/implement `PagingAndSortingRepository`
- [ ] For all matches add `CrudRepository` to the inheritance

````
interface Payments extends PagingAndSortingRepository<Payment<?>, Long> {
}
````

becomes

````
interface Payments extends PagingAndSortingRepository<Payment<?>, Long>, CrudRepository<Payment<?>, Long> {
}
````

**Comment by simi1912** [comment]
Why this happend?

**Comment by fabapp2** [comment]
> Why this happend?

It's explained in the Release Notes.
