### ISSUE TITLE
Version for spring-boot-maven-plugin must be set when Boot dependencies are added by 

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#284]
**Describe the bug**
The recipe `initialize-spring-boot-migration` must set the version for the `spring-boot-maven-plugin` to the current Spring Boot version.

**To Reproduce**
Run the recipe against a non-Spring application.
`spring-boot-maven-plugin` has no version.
````
<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                ...
           </plugin>    
````

**Expected behavior**
The version for `spring-boot-maven-plugin` should be explicitly set to the Spring Boot version used.

````
<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
           </plugin>    
````

**Additional context**
When Spring Boot dependencies are imported using a `dependencyManagement` section instead of parent pom the version of plugins is not managed and must be explicitly set

reported-by: @andreasf

**Comment by ahmedmq** [comment]
hey @fabapp2 - Can i work on this issue?

**Comment by fabapp2** [comment]
Hi @ahmedmq !

That would be awesome 🚀 
Please don't hesitate to ask in case you have questions or need clarification.

**Comment by fabapp2** [comment]
assigned-to: @ahmedmq

**Comment by ahmedmq** [comment]
Hey @fabapp2 

I noticed that the test `InitializeSpringBootMigrationRecipeIntegrationTest` passes but it actually does not compare the migrated code and the expected code(`empty-project`). Are you aware of it? I can fix this as part of this issue

**Comment by fabapp2** [comment]
Hi @ahmedmq

thanks for this finding! 
Maybe the tests need tests here ;) 
I am more than happy if you could look into this. 
Can we use this [this issue](https://github.com/spring-projects-experimental/spring-boot-migrator/issues/457)? 
For better reference and review. I assigned you to it, hope that's ok?

**Comment by ahmedmq** [comment]
Hey @fabapp2 - That should be perfectly fine. I have submitted a pull request. Please let me know if you need any changes
