### ISSUE TITLE
`BuildFile.addDependencies(...)` should not add existing dependency again

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#309]
To reproduce:

- `apply migrate-jpa-...` (adds `spring-boot-starter-data-jpa`)
- `apply migrate-stateless-ejb`(adds `spring-boot-starter-data-jpa` again to resolve `@Transactional`)  

````
BuildFile bf = retrieveBuildFile();
bf.addDependency(Dependency.builder()); // e.g. add `foo:bar:1.0`
bf.addDependency(Dependency.builder()); // e.g. add `foo:bar:1.0` again
````

will add the dependency `foo:bar:1.0` twice

**Comment by fabapp2** [comment]
Currently, the implementation will add a dependency with `compile` scope when the same dependency already exists with `test` scope. 

- [ ] It should merge these dependencies and set the state accordingly (or throw exception?)

**Comment by ravig-kant** [comment]
Hi @fabapp2 

Here are my initial thoughts. OpenRewriteMavenBuildFile `OpenRewriteMavenBuildFile.containsDependency` logic should be changed as follow.

- [ ] If the given Dependency is added to the test scope
    - [ ] Lookup in compile scope and no-op if found
    - [ ] Lookup in test scope and no-op if found
    - [ ] Add dependency to the test scope
- [ ] If the Dependency is added to the compile scope
    - [ ] Lookup in the test scope. If found, remove from test scope and add to the compile scope
    - [ ] Lookup in the compile scope. If found no-op
    - [ ] Add to the compile scope
- [ ] If the Dependency is added without specifying the scope
   - [ ]  Lookup in the test scope. If found, throw an exception that dependency already exists in the test scope
   - [ ] Lookup in the compile scope. If found no-op
   - [ ] Add to the compile scope

Let me know your thoughts.
