### ISSUE TITLE
`IsMatchingSpringBootVersion` fails with pom.xml having only Spring Boot declared in `dependencyManagement`

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#423]
**Describe the bug**
Scanning an application that has the dependency to Spring Boot declared in `dependencyManagement` but not other dependency to Spring Boot fails. 

Also the check for spring-modules takes the version into account but uses a finder that checks only declared dependencies. 
But in most cases declared dependencies to Spring modules will not have a version declared and this check will then fail. 
Replacing the finder with a finder that searches the resolved dependencies with version and not only declared dependencies would fix this

## To reproduce

**Given:**

````
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.springframework.sbm</groupId>
    <artifactId>spring-boot-migrator</artifactId>
    <version>0.12.1-SNAPSHOT</version>
    <dependencyManagement>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.7.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    </build>
</project>
````

When running `boot-2.7-3.0-dependency-version-update` 

**Then:** 
nothing changes

**Expected:**
Version updated and repository added (if required)

**Comment by fabapp2** [comment]
Assigned to @sanagaraj-pivotal

**Comment by sanagaraj-pivotal** [comment]
[demo.zip](https://github.com/spring-projects-experimental/spring-boot-migrator/files/9673710/demo.zip)

Tested with above project, it is working as expected
