### ISSUE TITLE
3.0.0-M5: Changes to Data properties

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#441]
From [Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#changes-to-data-properties)

>The data prefix has been reserved for Spring Data and any properties under the `data` prefix imply that Spring Data is required on the classpath.

## What needs to be done

When properties starting with `spring.data.` exist but no dependency to `org\\.springframework\\.data\\:.*` exists on the classpath, create a warning in the report.

>The scan found these properties starting with `data.` {list properties found} but no  dependency matching {used regex} on the classpath. 
The data prefix has been reserved for Spring Data and any properties under the `data` prefix imply that Spring Data is required on the classpath.
Please rename the properties and choose a prefix different to `data.` if `spring-data` is not required on the classpath.

## Additional information
[`DatabaseDriverGaeFinder`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/02d6969db26c6e85acaa0fb0beeb44eba7235835/components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade_27_30/checks/DatabaseDriverGaeFinder.java)

[`DatabaseDriverGaeSectionBuilder`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/02d6969db26c6e85acaa0fb0beeb44eba7235835/components/sbm-recipes-boot-upgrade/src/main/java/org/springframework/sbm/boot/upgrade_27_30/checks/DatabaseDriverGaeSectionBuilder.java)

**Comment by kuldeepsidhu88** [comment]
@fabapp2 I could see **Changes to Data Properties** section in boot-new-report.yaml.
https://github.com/spring-projects-experimental/spring-boot-migrator/blob/main/components/sbm-recipes-boot-upgrade/src/main/resources/recipes/boot-new-report.yaml#L89-L108

 Is there anything else pending on this?

**Comment by fabapp2** [comment]
@kuldeepsidhu88 thanks for asking (and making me aware). It looks done to me.
I am a bit behind and the current backlog is as well, unfortunately. 
The reason is that we focused on implementing a new Spring Boot 3 Upgrade approach using the report you linked which was moved [here](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/webapp-demo/components/sbm-recipes-boot-upgrade/src/main/resources/recipes/27_30/report/sbu30-report.yaml). we moved (maybe too) fast and things became a bit messy. The branch is still open, but I plan to merge it into the main branch next few days and will clean up the backlog and close this and potentially other finished issues. 
Did you plan to work on something/this? If so, I could create or provide an issue you could work on without hitting roadblocks.

**Comment by fabapp2** [comment]
closed with #553
