### ISSUE TITLE
3.0.0-M5: Cassandra Properties

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#442]
from the [Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#cassandra-properties)

>Configuration Properties for Cassandra have moved from `spring.data.cassandra.` to `spring.cassandra.`.

## What needs to be done
Find all properties with prefix `spring.data.cassandra.` and change the prefix to `spring.cassandra.`

**This should be done as (integrated) declarative plain OpenRewrite recipe**

See: 
https://github.com/spring-projects-experimental/spring-boot-migrator/blob/f219382c2b3e4ddffe8efed7b6c0ebe2e96f363c/components/sbm-recipes-boot-upgrade/src/main/resources/recipes/boot-2.7-3.0-dependency-version-update.yaml#L82-L95

**Comment by kuldeepsidhu88** [comment]
@fabapp2 I would like to contribute for this, can you please assign it to me. 
May need your help along the way as it would be my first time.

**Comment by fabapp2** [comment]
Hi @kuldeepsidhu88 !
Thanks for your interest 🚀 
Happily assigned to you.

Just post a new message in case you have any questions and I will try to help. 
Please also see #446

**Comment by kuldeepsidhu88** [comment]
@fabapp2 I have created draft PR with the changes. Please review.
