### ISSUE TITLE
3.0.0-M5: Redis Properties

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#443]
labels: ["type: enhancement","good first issue","upgrade:boot-recipe","3.0.0"]

From the [Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#redis-properties)

>Configuration Properties for Redis have moved from `spring.redis.` to `spring.data.redis.` as redis auto-configuration requires Spring Data to be present on the classpath.

## What needs to be done
Find all properties with prefix `spring.redis.` and change the property to use the prefix `spring.data.redis.`.

**This should be done as (integrated) declarative plain OpenRewrite recipe**

See: 
https://github.com/spring-projects-experimental/spring-boot-migrator/blob/f219382c2b3e4ddffe8efed7b6c0ebe2e96f363c/components/sbm-recipes-boot-upgrade/src/main/resources/recipes/boot-2.7-3.0-dependency-version-update.yaml#L82-L95

**Comment by kuldeepsidhu88** [comment]
@fabapp2 I can work on this. Can you please assign this to me.

**Comment by fabapp2** [comment]
Hi @kuldeepsidhu88 

OpenRewrite has recently solved the problem of reading property changes from metadata information contained in jars.
Property changes in Spring Boot are documented in a [`spring-configuration-metadata.json` file](https://github.com/spring-projects/spring-boot/blob/604aa4d51244c2b485dec22892258fd501a39b9f/spring-boot-project/spring-boot-tools/spring-boot-properties-migrator/src/main/java/org/springframework/boot/context/properties/migrator/PropertiesMigrationListener.java#L80) and they read them from the jars of the relevant version to create property update recipes out of these files.
This means we'd be reinventing the wheel with more recipes for property updates.

I haven't yet looked into it in detail but I guess I'll need to upgrade to the latest Rewrite to use their solution for migration recipes. That's on my list and I'd like to wait and see if we can reuse their recipe before we provide more of these recipes ourselves.

We decided to go "report-first" for now, so these changes should also be provided in a report (first). 
I would like to see if we can use a similar (or even their) approach to generate the report section(s) that highlight relevant property changes in the report to users. If this works we could skip all property updates (migration & report) and generate them from the metadata information.

Looking at your timestamp makes me think we're in different time zones. Meaning I will try to provide more issues (and probably close some old ones) to reflect our "report-first" approach in the (currently bit messy) backlog today (🤞). 
I am still lacking behind but I will try to provide an issue that would be more important at the moment, hoping you might be willing to look into it instead. (🤞)

**Comment by kuldeepsidhu88** [comment]
Sure @fabapp2 
Please let me know which issue can be picked next, I would be happy to contribute.

**Comment by kuldeepsidhu88** [comment]
@fabapp2 Okay, I will start looking into #248
