### ISSUE TITLE
3.0.0-M5: JMX Endpoint Exposure

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#444]
From the [Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#jmx-endpoint-exposure)

>By default, only the health endpoint is now exposed over JMX, to align with the default web endpoint exposure. This can be changed by configuring the `management.endpoints.jmx.exposure.include` and `management.endpoints.jmx.exposure.exclude` properties.

## What needs to be done
To guarantee that JMX endpoint exposure is exactly the same as prior to 3.0 the settings in 2.7 should be restored and the user should be warned about the implications and how to secure JMX endpoints.

#### Condition
Application is a Spring Boot 3.0.0 application and `management.endpoints.jmx.exposure.include` is not set.

#### Section
>By default, only the health endpoint is now exposed over JMX, to align with the default web endpoint exposure. This can be changed by configuring the `management.endpoints.jmx.exposure.include` and `management.endpoints.jmx.exposure.exclude` properties.
As Spring Boot Migrator can't tell if the JMX endpoints provided in 2.7 are used, the recipe will restore the defaults as in 2.7 by setting `management.endpoints.jmx.exposure.include=*`. This exposes all management endpoints over JMX. To provide only required information over JMX we strongly recommend to configure the `management.endpoints.jmx.exposure.include` property to your specific needs and only expose required JMX endpoints.
Please consult the reference documentation [Spring Boot 3.0.0-M5](https://docs.spring.io/spring-boot/docs/3.0.0-M5/reference/htmlsingle/#actuator.endpoints.exposing) or after 3.0.0 is GA: [Spring Boot 3.0.0](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.endpoints.exposing)

#### Condition
Application is a Spring Boot 3.0.0 application and `management.endpoints.jmx.exposure.include` is not set.

#### Action
- [ ] Set `management.endpoints.jmx.exposure.include=*` in `application.properties`

**Comment by ishu-thakur** [comment]
Hi @fabapp2 , i would like to work on this one .
so you want me to set management.endpoints.jmx.exposure.include=* in every single or all application.properties that exist in the spring-boot-migrator or there is some  specific ones in which you want me to set that ?

**Comment by fabapp2** [comment]
Hi @ishu-takur,

thank you for your picking this issue! 🚀

As application.yaml/application.properties contain the properties for 'default' profile (which will be used until overwritten by another profile) it should be enough to set the property there. If more than one application.properties/.yaml exists it should be set in all of them (hard to calculate if they are ending up in digferent deployables) which should be sufficient.
It is important to inform the user about the implications (especially as it is security related), therefor the report.

Thanks again for picking this!
Please don't hesitate to ask questions and provide feedback.

**Comment by fabapp2** [comment]
Please have a look at

**Comment by fabapp2** [comment]
Hi @ishu-thakur 

It's great you ask to clarify!
The issue consists of basically two "things". 

1. Creating a report, see the **Report** in the issue and additionally the #446 discussion where I linked an example implementation. A report consists of multiple sections and these sections can be created like in the example classes.
2. Then there's the recipe (the automation you're asking about). The access to properties is abstracted by `SpringBootApplicationProperties`which can be retrieved from the `ProjectContext` using a `Finder`, here `SpringBootApplicationPropertiesResourceListFilter` (the name should be changed to `SpringBootApplicationPropertiesResourceListFinder`). The `SpringBootApplicationProperties` provides the API to add the property to the default properties. (Yaml will be abstracted as well, just not there yet)

Creating the report should be straightforward looking at the linked example classes. 🤞 

For the migration recipe:
- [ ] Create a new `Boot_27_30_JmxEndpointExposureAction` extending `AbstractAction` and implement the mentioned logic there
- [ ] Implement the condition as described in the issue (or reuse the one from the report if possible)
- [ ] Provide a test using `TestProjectContext` if possible for single and multi-module projects
- [ ] Add the new Action to the recipe declaration in [`boot-2.7-3.0-dependency-version-update.yaml`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/5f6594d5233b6449fcb01d1b97f795b01a4c0147/components/sbm-recipes-boot-upgrade/src/main/resources/recipes/boot-2.7-3.0-dependency-version-update.yaml)
- [ ] Add the migration to the `BootUpgrade_27_30_...` integration tests, e.g.  [`BootUpgrade_27_30_ManuallyManaged_IntegrationTest`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/5f6594d5233b6449fcb01d1b97f795b01a4c0147/applications/spring-shell/src/test/java/org/springframework/sbm/BootUpgrade_27_30_IntegrationTest.java)


As I mentioned, feel free to ask anything anytime. You can also provide a draft PR in case you have questions or need feedback early on.

Hope this was helpful?

**Comment by DevPJ9** [comment]
Hello @fabapp2 I would also like to work on this issue and will be syncing with @ishu-thakur for this issue.

**Comment by fabapp2** [comment]
> Hello @fabapp2 I would also like to work on this issue and will be syncing with @ishu-thakur for this issue.

Hi @DevPJ9,
thanks for your interest. 🚀
If you know @tishu-thakur and want to pair on this (or sync somehow), totally fine. Otherwise I'd think you'll probably step on each other's toes and it might make sense to pick something else. If you're uncertain how to contribute I am more than happy to help you out and get you started.

**Comment by DevPJ9** [comment]
Hello @fabapp2.I know @ishu-thakur and will be able to sync with him. Thanks for your suggestion and support.

**Comment by fabapp2** [comment]
Hi @ishu-thakur 
let me add some information to #446. 
Could you let me know if I missed something you need to know?

**Comment by ishu-thakur** [comment]
@fabapp2 is there any documentation that tell how we can run the project or file to test the logic for JMX endpoint exposure i have created as the test case file doesn't seems to runnable :(

**Comment by fabapp2** [comment]
Hi @ishu-thakur 
Thanks for asking these questions!
Your questions highlighted more missing bits in #446 
I will answer your questions there, hoping it's helpful for others.

**Comment by fabapp2** [comment]
Hi @ishu-thakur 
I added links to some resources and documentation. 
Please let me know if you miss something.
This issue goes in both, report and upgrade recipe yaml and has two separate (Finder might be reused though) components.
#446 links a simple example for the report part under "Report", you don't need to touch the yaml here.
The migration bit will require you to implement the property change for single and multi-module applications.

Here it could be done like this (🤞):

```java
// get spring boot application property files
List<SpringBootApplicationProperties> applicationProperties = context.search(
                new SpringBootApplicationPropertiesResourceListFilter());
         
applicationProperties.stream()
                // filter the properties files for default profile
                .filter(p -> p.isDefaultProperties())
                // and add the property
                .forEach(p -> p.setProperty("...", "..."));
```

For The Action (migration) you'll need to provide a condition (also in yaml) in the package you named. 
For the report there's the concept of `Finder`s which can be used as condition (and thus be used for report and migration).
These provide the matches and if there are no matches it's not applicable.

If you like you can just create a draft PR with what you have and I can answer questions and provide feedback on concrete code, might be easier.

**Comment by fabapp2** [comment]
@ishu-thakur you must add 
```java
.addRegistrar(new SpringBootApplicationPropertiesRegistrar(new SpringApplicationPropertiesPathMatcher()))
```
to make `TestProjectContext` init the `SpringBootApplicationProperties`

**Comment by ishu-thakur** [comment]
> SpringBootApplicationProperties

@fabapp2  while i am writing the testcase for the jmx exposure ? then i should add .`addRegistrar(new SpringBootApplicationPropertiesRegistrar(new SpringApplicationPropertiesPathMatcher()))` ?

**Comment by fabapp2** [comment]
> > SpringBootApplicationProperties
> 
> @fabapp2 while i am writing the testcase for the jmx exposure ? then i should add .`addRegistrar(new SpringBootApplicationPropertiesRegistrar(new SpringApplicationPropertiesPathMatcher()))` ?

Correct, otherwise "specialized resource" `SpringApplicationProperties` will not be found by the `Finder`

**Comment by ishu-thakur** [comment]
@fabapp2 its okay I hope you have enjoyed your vacation :) yes let me figure it out and make changes then .
