### ISSUE TITLE
Merge scopes when adding a dependency that exists but with different scope

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#455]
Currently, the implementation will add a dependency with `compile` scope when the same dependency already exists with `test` scope. It should merge these dependencies and set the state accordingly (or throw exception?)

_Originally posted by @fabapp2 in https://github.com/spring-projects-experimental/spring-boot-migrator/issues/309#issuecomment-1262845641_

**Comment by ravig-kant** [comment]
Hi @fabapp2 

Any takers for this? Otherwise, I will give it a shot.

**Comment by fabapp2** [comment]
HI @ravig-kant !
Thank you for picking this up. 🚀 
The description is rather minimal. 
Please don't hesitate to ask

assigned-to: @ravig-kant

**Comment by ravig-kant** [comment]
Hi @fabapp2 

Here are my initial thoughts. OpenRewriteMavenBuildFile `OpenRewriteMavenBuildFile.containsDependency` logic should be changed as follow.

- [ ] If the given Dependency is added to the test scope
    - [ ] Lookup in compile scope and no-op if found
    - [ ] Lookup in test scope and no-op if found
    - [ ] Add dependency to the test scope
- [ ] If the Dependency is added to the compile scope
    - [ ] Lookup in the test scope. If found, remove from test scope and add to the compile scope
    - [ ] Lookup in the compile scope. If found no-op
    - [ ] Add to the compile scope
- [ ] If the Dependency is added without specifying the scope
   - [ ]  Lookup in the test scope. If found, throw an exception that dependency already exists in the test scope
   - [ ] Lookup in the compile scope. If found no-op
   - [ ] Add to the compile scope

Let me know your thoughts.

**Comment by fabapp2** [comment]
> Hi @fabapp2
> 
> Here are my initial thoughts. OpenRewriteMavenBuildFile `OpenRewriteMavenBuildFile` logic should be changed as follow.
> 
> * [ ]  If the given Dependency is added to the test scope
>   * [ ]  Lookup in compile scope and no-op if found
>   * [ ]  Lookup in test scope and no-op if found
>   * [ ]  Add dependency to the test scope
> * [ ]  If the Dependency is added to the compile scope
>   * [ ]  Lookup in the test scope. If found, remove from test scope (or change scope to compile?)
>   * [ ]  Lookup in the compile scope. If found no-op
>   * [ ]  Add to the compile scope
> * [ ]  If the Dependency is added without specifying the scope 

The scope is then set to `compile` in `OpenRewriteMavenBuildFile:437`:
`dependency.getScope() == null ? "compile" : dependency.getScope(),`

>   * [ ]   Lookup in the test scope. If found, throw an exception that dependency already exists in the test scope

Why not changing it to compile?

>   * [ ]  Lookup in the compile scope. If found no-op
>   * [ ]  Add to the compile scope
> 
> Let me know your thoughts.

Hi @ravig-kant 

thanks for looking into it!
I looked into [Baeldung](https://www.baeldung.com/maven-dependency-scopes) and this would be the change matrix I (think) I understood. It states that `system` is deprecated and I think we can ignore it if it is unclear or gives us a headache.
I am not completely sure about the implications with transitive dependencies and scope settings in `dependencyManagement` and would need to consult the latest documentation. 
But, if we use the effective dependencies these settings in transitive and managed should be reflected and this shouldn't be an issue (I recall that explicit scope overwrites scope in `managedDependencies` 🤔). 


| current / given | provided                 | compile                  | test                     | system                   | import                |
|-----------------|--------------------------|--------------------------|--------------------------|--------------------------|-----------------------|
| provided        |                          |                          |                          | system                   | added with type="pom" |
| compile         | provided                 |                          |                          | system                   | added with type="pom" |
| test            | provided                 | compile                  |                          | system                   | added with type="pom" |
| system          | provided                 |                          |                          |                          | added with type="pom" |
| import          | added without type="pom" | added without type="pom" | added without type="pom" | added without type="pom" | added with type="pom" |

Let me know your thoughts. 😃

**Comment by ravig-kant** [comment]
> > Hi @fabapp2
> > Here are my initial thoughts. OpenRewriteMavenBuildFile `OpenRewriteMavenBuildFile` logic should be changed as follow.
> > 
> > * [ ]   If the given Dependency is added to the test scope
> >   
> >   * [ ]   Lookup in compile scope and no-op if found
> >   * [ ]   Lookup in test scope and no-op if found
> >   * [ ]   Add dependency to the test scope
> > * [ ]   If the Dependency is added to the compile scope
> >   
> >   * [ ]   Lookup in the test scope. If found, remove from test scope (or change scope to compile?)

Agree. I meant to say remove from test scope and add to compile. 

> >   * [ ]   Lookup in the compile scope. If found no-op
> >   * [ ]   Add to the compile scope
> > * [ ]   If the Dependency is added without specifying the scope
> 
> The scope is then set to `compile` in `OpenRewriteMavenBuildFile:437`: `dependency.getScope() == null ? "compile" : dependency.getScope(),`
> 
> > * [ ]    Lookup in the test scope. If found, throw an exception that dependency already exists in the test scope
> 
> Why not changing it to compile?

Sure. Let's do that.
> 
> > * [ ]   Lookup in the compile scope. If found no-op
> > * [ ]   Add to the compile scope
> > 
> > Let me know your thoughts.
> 
> Hi @ravig-kant
> 
> thanks for looking into it! I looked into [Baeldung](https://www.baeldung.com/maven-dependency-scopes) and this would be the change matrix I (think) I understood. It states that `system` is deprecated and I think we can ignore it if it is unclear or gives us a headache. I am not completely sure about the implications with transitive dependencies and scope settings in `dependencyManagement` and would need to consult the latest documentation. But, if we use the effective dependencies these settings in transitive and managed should be reflected and this shouldn't be an issue (I recall that explicit scope overwrites scope in `managedDependencies` 🤔).
> 
> current / given	provided	compile	test	system	import
> provided				system	added with type="pom"
> compile	provided			system	added with type="pom"
> test	provided	compile		system	added with type="pom"
> system	provided				added with type="pom"
> import	added without type="pom"	added without type="pom"	added without type="pom"	added without type="pom"	added with type="pom"
> Let me know your thoughts. 😃

Hi @fabapp2 

If we are promoting a dependency from transitive to direct, it should not be an issue. Direct dependencies take precedence over transitive dependencies.
A dependency in 'dependencyManagement' can be in the same build file, or parent projects build file. In the former case, I think we should update the 'depedencyManagement' section. For the latter, we can override, but the users should be informed about this change.
Let me know your thoughts.

**Comment by ravig-kant** [comment]
Hi @fabapp2 

While implementing the change, I got some doubts about your proposed change matrix :). The first column represents the scope of the dependency in the current state, while the first row represents the proposed change. 

For instance, if a dependency is currently in _compile_ scope and it's now being added in _provided_ scope, as per the matrix, the updated pom will have _provided_ scope. Is it correct?

Ravi

**Comment by fabapp2** [comment]
Hi @ravig-kant 

Sorry for my late response, I was on vacation.

Maybe I overdid the requirement a bit 🤔 
- 👍 For ignoring `system` scope.
- For Spring Boot provided scope will have the same effect as compile, given [this comment](https://github.com/spring-projects/spring-boot/issues/413#issuecomment-36361340)
- 👍 For not modifying `import` scope. I am not sure (actually I doubt) if there's a valid case to define the same dependency (pom) as `import` and any other scope.

If these assumptions are correct, I guess we're back to the requirements you initially defined?! 😃

**Comment by ravig-kant** [comment]
Hi @fabapp2 

I think I was too eager to make some progress 😅 . I just put together a tiny algorithm which works as below.

- [ ]  Look up matching existing dependencies for a proposed new dependency. The match currently is being done based on the groupId and artefact.
- [ ] The matches are looked in the effective dependencies. So transitive are also checked. These potential matches are candidates and will decide the action ( upsert/no-op) for the proposed new dependency.
- [ ] Maintain a matrix of scopes which tells which other scopes a given scope supersedes. For instance, a **_compile_** scope supersedes any existing entries with **_Test_**, **_Provided_** and **_Runtime_** scope.
- [ ] If the proposed dependency supersedes the existing dependency, then perform an upsert operation otherwise, its a no-op
- [ ] If there are no potential candidates, add the proposed dependency.

You can look at [this code](https://github.com/ravig-kant/spring-boot-migrator/blob/main/components/sbm-core/src/main/java/org/springframework/sbm/build/api/DependencyChangeResolver.java) which implements this algorithm. I think this algorithm satisfies the asks in this enhancement and can be extended for any future asks. 

Thanks
Ravi

**Comment by fabapp2** [comment]
Ha! I like your attitude 💪 

I need to look at your code next few days, as being a bit behind due to my vacation.

**Comment by fabapp2** [comment]
Hi @ravig-kant 

looks nice clean and concise. 🤩 
Could you add tests, embed it into a recipe (yaml?), and create a PR?

**Comment by ravig-kant** [comment]
Hi @fabapp2 

Raised [pr](https://github.com/spring-projects-experimental/spring-boot-migrator/pull/533). I have changed the _AddDependency_ action instead of creating a new recipe. 
The assumption is that the recipes will use the _AddDependency_ action. I want to understand more about **MultiModuleAwareAction**. Can you provide some document pointers to understand it?
There are two APIs to add a dependency. One is, of course, _AddDependency_ action. Another is the _BuildFile_ interface. What is the difference between the two? I wanted to change the `OpenRewriteBuildFile.addDependency` implementation, but I was unsure about its existence.
