### ISSUE TITLE
Refactor: Remove `addDefaultPropertiesFileToTopModules` flag

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#461]
### What needs to be done
Replace the `addDefaultPropertiesFileToTopModules` flag in `AddSpringBootApplicationPropertiesAction` with 

````
if(context.getApplicationModules().isSingleModuleApplication()) {
  context.getApplicationModules()
                    .getRootModule()
                    ...
} else {
  context.getApplicationModules()
                    .getTopmostApplicationModules()
                    .stream()
                    .forEach(this::apply);
}
````

**Comment by AbhiVaidya95** [comment]
Hey @fabapp2 , I can pick this up?

**Comment by fabapp2** [comment]
> Hey @fabapp2 - Can I pick this one?

picked-by: @ahmedmq

**Comment by fabapp2** [comment]
> Hey @fabapp2 , I can pick this up?

@AbhiVaidya95 thanks for your interest. 🚀

Could you pick sonething else maybe? This issue came up after a change @ahmedmq did, so he's got all context.
I will update issues next days in case there's nothing that interests you now.

**Comment by ahmedmq** [comment]
Thanks @fabapp2
