### ISSUE TITLE
Considering using a more inclusive emoji for the manual recipes

### ISSUE THREAD

**Issue by RUBenGAMArrarodRiguEZ-ToMtOm** [spring-projects-experimental/spring-boot-migrator#525]
### What needs to be done
Change the emoji

### Why it needs to be done
so persons that use this experimental project are more encouraged to do the not-automated recipes, regardless of their number of arms 0️⃣1️⃣2️⃣, prosthetic or not 🦾, the color of their skin and how much muscle they have.

---
### Acceptance Criteria

/info panel
**Given** precondition
**When** action
**Then** result

**Comment by RUBenGAMArrarodRiguEZ-ToMtOm** [comment]
Proposal here https://github.com/spring-projects-experimental/spring-boot-migrator/pull/524

**Comment by fabapp2** [comment]
Hi @RUBenGAMArrarodRiguEZ-ToMtOm

Thank you for this great idea! 
To be honest with you I just learned about this emoji an hour ago while searching for other emojis online.

**Comment by fabapp2** [comment]
\uD83D\uDCA6 is not \ud83e\uddbe

**Comment by fabapp2** [comment]
Hm, seems I am not an emoji expert... took me a moment to understand. 
Not sure if I agree but let's go for "sweat" as I don't mind either.
