### ISSUE TITLE
JAX-RS QueryParam annotation is always converted into a mandatory RequestParam

### ISSUE THREAD

**Issue by bottemav** [spring-projects-experimental/spring-boot-migrator#528]
**Describe the bug**
After applying the recipe `migrate-jax-rs` , every JAX-RS annotation `QueryParam` is converted into an annotation `RequestParam` without the attribute `required` which defaults to `true`.

**To Reproduce**
1. Checkout https://github.com/bottemav/spring-boot-migrator/tree/bugfix/jax-rs_required
2. Run `MigrateJaxRsIntegrationTest`
3. The method
```
    @GET
    @Produces(APPLICATION_JSON)
    @Path("/list")
    public List<String> listCompanies(
            @QueryParam("q") String searchBy,
            @QueryParam("sort") String sort) {
        return Collections.emptyList();
    }
```
is converted into
```
    @RequestMapping(produces = APPLICATION_JSON, value = "/list", method = RequestMethod.GET)
    public List<String> listCompanies(
            @RequestParam(value = "q") String searchBy,
            @RequestParam(value = "sort") String sort) {
        return Collections.emptyList();
    }
```

**Expected behavior**
The annotation `RequestParam` contains the attribute `required` with value `false`
```
    @RequestMapping(produces = APPLICATION_JSON, value = "/list", method = RequestMethod.GET)
    public List<String> listCompanies(
            @RequestParam(value = "q", required = false) String searchBy,
            @RequestParam(value = "sort", required = false) String sort) {
        return Collections.emptyList();
    }
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11
 - JDK: GraalVM Java17 22.2.0

**Additional context**
`MigrateJaxRsRecipe` already contains code to add the `required` attribute but it seems as if it is never executed. Even when I remove  `addOnly: true` from the recipe and change the condition to `Condition.TRUE`, the `required` attribute is never added.

**Comment by fabapp2** [comment]
Hi @bottemav 

Thanks for reporting. 
I realised this too and (literally) hacked something. If you run the recipe again it will set the `required=false` attribute. There's obviously something wrong as the action should run with the others but the code exists.
I don't have time to look into it at the moment but I guess it shouldn't be too hard to fix it (and remove the need to re-run the recipe). 
I am happy to assist if you want to look into it and maybe contribute a fix yourself?

**Comment by bottemav** [comment]
Hi @fabapp2,

It seems that AddOrUpdateAnnotationAttribute recipe needs to run multiple times to deliver the desired result if the recipe is applied to an annotation with a value. I created an issue on the openrewrite project as to me, it's a bug on the recipe itself.

Awaiting a solution by the openrewrite project, I will create a PR to add the attribute `causesAnotherCycle: true` to the recipe.

**Comment by fabapp2** [comment]
Hi @bottemav 
Great you solved this, thank you for the contribution! 🚀
