### ISSUE TITLE
MIgrate all properties to @Stateless when migrating ejb-jar.xml to annotation

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#56]
### What needs to be done
All possible attributes for stateless session bean declarations given in an EJB deployment descriptor (`ejb-jar.xml`) must be migrated to annotations when `migrate-ejb-jar-deployment-descriptor` is applied.

### Why it needs to be done
Currently, only `beanName` attribute is migrated. 
If an `ejb-jar.xml` contains additional attributes these are not migrated and the migration is broken/incomplete.

### Additional Information
See `MigrateEjbDeploymentDescriptor.handleStatelessSessionBean()`

**Comment by ravig-kant** [comment]
Hi @fabapp2 

I will take a stab at it.

**Comment by ravig-kant** [comment]
Hi @fabapp2 

Is there any test to validate the changes?
