### ISSUE TITLE
JAX-RS: migrate DefaultValue annotation on request parameters

### ISSUE THREAD

**Issue by bottemav** [spring-projects-experimental/spring-boot-migrator#574]
### What needs to be done
Migrate `javax.ws.rs.DefaultValue` annotation on request parameters to the `defaultValue` attribute of `org.springframework.web.bind.annotation.RequestParam`

### Why it needs to be done
javax.ws.rs.DefaultValue is one of the JAX-RS annotations that needs to be migrated to Spring Web. The annotation can be applied to a couple of request annotations like QueryParam, FormParam, PathParam, ... but let's start with QueryParam.

### Acceptance Criteria
After applying the recipe, the RequestParam annotation has a `defaultValue` attribute with the same value as the `javax.ws.rs.DefaultValue` annotation and the `javax.ws.rs.DefaultValue` annotation is removed.

**Given** a method parameter annotated with both `javax.ws.rs.DefaultValue` and `javax.ws.rs.QueryParam` annotations
**When** the recipe MigrateJaxRsRecipe is applied
**Then** the method parameter is annotated with a `org.springframework.web.bind.annotation.RequestParam` having an `defaultValue` attribute with the same value as the `javax.ws.rs.DefaultValue annotation` 

### Additional Information
An example:
`public String getAllPersons(@DefaultValue("0") @QueryParam("page") int page)`
should be migrated to
`public String getAllPersons(@RequestParam(required = false, value = "page", defaultValue="0") int page)`

**Comment by fabapp2** [comment]
Thanks for adding this @bottemav
It's a long way to fully migrate JAX-RS to Boot... 
would you like to look into it and contribute something as another step in this direction?

**Comment by bottemav** [comment]
@fabapp2 Sure, I'd love to.

I think I will create a new Recipe for this

```
MoveAnnotationAttribute (
   String sourceAnnotation,
   String sourceAnnotationAttribute,
   String targetAnnotation,
   String targetAnnotationAttribute,
   boolean removeSourceAnnotation
)
```

For this ticket it will be used this way:

```
MoveAnnotationAttribute (
   "javax.ws.rs.DefaultValue", "value", "org.springframework.web.bind.annotation.RequestParam", "defaultValue", true
);
```

I'm still in doubt whether removing the source annotation is part of the recipe or not.

**Comment by fabapp2** [comment]
HI @bottemav 

I like the idea of implementing a generic recipe.
IMHO it should be an isolated step and not combined with deleting the recipe.
Mainly because I could imagine a composition of these recipes where multiple annotation attributes need to be moved and then you wouldn't want to delete the annotation straight away but do it in a separate step. 
A quick check made me realize a `DeleteAnnotaion` does not exist. 
I am more than open to discussing in case you have a different opinion.
I will assign this issue to you. Thanks for contributing 🚀

**Comment by fabapp2** [comment]
@bottemav if you like you can join our [Slack](https://join.slack.com/t/springbootmigrator/shared_invite/zt-1k6yxfi3b-MEQ_MM67qXufWtc~Tw6y9w) for faster/easier communication.
