### ISSUE TITLE
Maven settings -> localRepository is not evaluated

### ISSUE THREAD

**Issue by fiveOO** [spring-projects-experimental/spring-boot-migrator#582]
In `~/.m2/settings.xml` the path of the local repository (`~/.m2/repository` by default) could be customized to another directory by using
```
<settings>
   <localRepository>/another/directory/to/be/used</localRepository>
   ...
</settings>
```
If `localRepository` is set the given path should be used to locate the repository instead of `~/.m2/repository`. The migrator ignores this setting.

**Comment by fabapp2** [comment]
Thanks for reporting @fiveOO 🚀 

I will look into it.

**Comment by fiveOO** [comment]
A possible workaround could be to create a symbolic link to let migrator "think" that the repository folder is where expected.
`mklink /d C:\Users\myusername\.m2\repository D:\temp\devCacheRoot\m2Repo` worked for me.

**Comment by fabapp2** [comment]
Hi @fiveOO, 
I tweaked the recently added `MavenSettingsInitializerTest` and it works (on my machine). 
Could you do me a favour and run this test on Windows to see if it succeeds? 
It's currently building here #584.
I am on Mac and currently have no good option to test under Windows.
If the test succeeds but the problem persists we can further investigate what the issue could be.
Glad you found a way to circumvent this issue. Nevertheless, I'd be up to seeing if we can find a more stable solution.

**Comment by fabapp2** [comment]
I should have asked earlier... did you try 0.12.0 where `settings.xml` was not read at all, or latest `main` where it was recently added? Preparing a Release just now. Maybe that fixes it for you 🤞

**Comment by fiveOO** [comment]
Unfortunately, the current HEAD does not solve the issue (but file system link is still working).

**Comment by fiveOO** [comment]
#584 is running without an exception but it is creating a new folder `repository` in `.m2` and using it for retrieving artifacts.
Better would be to use the folder defined in `<localRepository>` for artifact resolution.

**Comment by fabapp2** [comment]
Caramba! Thanks for trying.
I agree, it should use the given folder. Let me investigate...

**Comment by fiveOO** [comment]
The test is producing the excepted results:
```
localRepository: file:///D:/temp/devCacheRoot/m2Repo/
D:\temp\devCacheRoot\m2Repo\jakarta\validation\jakarta.validation-api\3.0.2\jakarta.validation-api-3.0.2.jar
```
As I'm starting the migrator the folder `~/.m2/repository` is been created (just before the prompt gets visible).
At that moment it's still empty.
As soon as I'm starting the `scan` command a folder structure like a local repository is been created. I get 517 folders with no files at all. Only folders.

**Comment by fabapp2** [comment]
@fiveOO thanks for trying it and providing more details.
I think I will have to investigate a bit more and will tag you in a comment when I made any progress.

**Comment by fiveOO** [comment]
Most likely LocalMavenArtifactCache (created inside RewriteMavenArtifactDownloader) creates the folder as a cache folder.

**Comment by fabapp2** [comment]
> Most likely LocalMavenArtifactCache (created inside RewriteMavenArtifactDownloader) creates the folder as a cache folder.

Some misconfiguration with the hacky and customized caching would have been my guess too. I think this needs rework...

**Comment by fabapp2** [comment]
@sanagaraj-pivotal Could you pick this?

**Comment by sanagaraj-pivotal** [comment]
sure
