### ISSUE TITLE
3.0 Upgrade Recipe: thymeleaf-extras-springsecurity5 > 6

### ISSUE THREAD

**Issue by mhoshi-vm** [spring-projects-experimental/spring-boot-migrator#596]
labels: ["type: enhancement","good first issue","upgrade:boot-recipe","3.0.0"]

## What needs to be done

An automated migration recipe for thymeleaf-extras-springsecurity5 > 6 should be created.

### Condition
{{Describe when the section should be rendered}}

This did not get updated

```
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity5</artifactId>
        </dependency>
```

Should be

```
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity6</artifactId>
        </dependency>
```

### Report Section Issue

{{GH id for report issue}}

### DoD
- [ ] Action implemented
  - [ ] Description provided
  - [ ] Tests (single and multi-module)
- [ ] Condition implemented / reused
  - [ ] Description provided
  - [ ] Tests (single and multi-module)
- [ ] Recipe yaml added
  - [ ] Test
  - [ ] Integration test (single and multi-module) 

## Recipe YAML Example

This provides an example with information about how a automated migration recipe should be defined in `YAML`.

<details>
<summary>Report Section YAML (example)</summary>

````yaml

````

</details>

## Additional Resources & Information
- Example
- Testing Actions
- Testing Conditions
- Testing Recipes
- Integration Tests

**Comment by Dev-Arhaan** [comment]
Hi I am new to open source and would like to contribute... Can you tell me more about this project?

**Comment by mhoshi-vm** [comment]
It is project to for thymleaf to understand spring security, and tied to spring security 6 (which is also tied to spring boot 3)
