### ISSUE TITLE
3.0 Upgrade Report: Running Your Application in the Maven Process

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#666]
labels: ["type: enhancement","good first issue","3.0.0","upgrade:boot-report","generated"]

## What needs to be done
The auto-generated section in the Spring Boot 3 Upgrade Report for the 'Running Your Application in the Maven Process' section should be improved.

:warning: **Please read [Spring Boot 3 Upgrade Report Contribution Guideline](https://github.com/spring-projects-experimental/spring-boot-migrator/wiki/Spring-Boot-3-Upgrade-Report-Contribution-Guideline)** :warning:

[From the Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#running-your-application-in-the-maven-process)

> The `fork` attribute of `spring-boot:run` and `spring-boot:start` that was deprecated in Spring Boot 2.7 has been removed.

- The report is defined in [`components/sbm-recipes-boot-upgrade/src/main/resources/recipes/27_30/report/sbu30-report.yaml`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/main/components/sbm-recipes-boot-upgrade/src/main/resources/recipes/27_30/report/sbu30-report.yaml)
- The (generated) test is defined in [`components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/report/helper/RunningYourApplicationInTheMavenProcessReportSectionTest`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/main/components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/report/helper/RunningYourApplicationInTheMavenProcessReportSectionTest.java)

**Comment by bsmahi** [comment]
Hi @fabapp2 or @sanagaraj-pivotal 

I would like to pick up this enhancement. Please let me know your thoughts

Thanks,
Mahi

**Comment by sanagaraj-pivotal** [comment]
@bsmahi sounds awesome, go ahead. Please let me know if you need any help.

**Comment by fabapp2** [comment]
Hi @bsmahi,
thanks for your interest 🚀 

You can pick this up. 
Please read the linked contribution guideline and please provide feedback if something's unclear.

My thoughts on this:
- I'd see this section as always shown in the report because SBM can't tell if the `fork` flag is used anywhere outside of the app?
- The best SBM could do a search over all files and try to find a call to `spring-boot:run` maybe? I think everything else gets too complex for this edge case.

**Comment by bsmahi** [comment]
Hi @fabapp2 

Thanks for providing your thoughts.

Since you're on leave, I would like to connect and discuss with @sanagaraj-pivotal first as this is my task, I have few queries and get it clarified with Sandeep. 

Thanks,
Mahi

**Comment by fabapp2** [comment]
Hi @bsmahi 
I assigned this to you.

I think there's no reliable way to find usages of `fork`.
I see this issue and the related section defined in yaml as informative which is always shown and tells a user to check their scripts, especially build scripts for usages of `fork` with `mvn spring-boot:...`. 
Aditonally, it could link the relevant sections in docs and describe how to achieve the behaviour in 3.0 (if possible). 
Was this helpful, or do you have questions?

**Comment by bsmahi** [comment]
Hi @fabapp2 

Certainly, that was really helpful, I will check and get back to you.

Thank you so much :)

Mahi

**Comment by bsmahi** [comment]
Hi @fabapp2 

Have gone through the provided guidelines and this is my understanding.

* Since `fork` attribute has been deprecated in spring boot 2.7, we need to find way how to enable to `fork` by using SBM?

Please correct me if my understanding is right. And also, please let me know where to start the implementation. Feeling cumbersome. 

Thanks,
Mahi

**Comment by fabapp2** [comment]
Hi @bsmahi 
I hope you still want to look into this?
I found this [Issue](https://github.com/spring-projects/spring-boot/issues/34597) where Andy describes how the `fork` functionality can be replaced in 3.0.

Min.:
- Improve the generated report section by providing a description and a link to the Issue above.

If you want to do more:
- Scan `.sh` and `.bat` for usages of `mvn spring-boot:run` and then `fork` and list these matches in the section of the report.

Let me know if you want to pick this and if you have further questions?

**Comment by bsmahi** [comment]
Hi @fabapp2 

Certainly, I would like to pick it up. 

Before that, I'd like to talk with you about where I should start. I have no idea where to begin right now.

Could you please let me know how to connect with you for 30 mins.

Thanks,
Mahi

**Comment by fabapp2** [comment]
HI @bsmahi I sent you a PM on Slack

**Comment by bsmahi** [comment]
Hi @fabapp2 
Have raised a PR for the issue
https://github.com/spring-projects-experimental/spring-boot-migrator/pull/861
Could you please review it and let me know your feedback?
Thanks,
Mahi
