### ISSUE TITLE
3.0 Upgrade Report: Spring MVC and WebFlux URL Matching Changes

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#680]
## What needs to be done
The auto-generated section in the Spring Boot 3 Upgrade Report for the 'Spring MVC and WebFlux URL Matching Changes' section should be improved.

:warning: **Please read [Spring Boot 3 Upgrade Report Contribution Guideline](https://github.com/spring-projects-experimental/spring-boot-migrator/wiki/Spring-Boot-3-Upgrade-Report-Contribution-Guideline)** :warning:

[From the Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#spring-mvc-and-webflux-url-matching-changes)

> As of Spring Framework 6.0, the trailing slash matching configuration option has been deprecated and its default value set to `false`.
This means that previously, the following controller would match both "GET /some/greeting" and "GET /some/greeting/":

[source, java]
----
@RestController
public class MyController {

  @GetMapping("/some/greeting")
  public String greeting {
    return "Hello";
  } 

}
----

As of https://github.com/spring-projects/spring-framework/issues/28552[this Spring Framework change], "GET /some/greeting/" doesn't match anymore by default.

Developers should instead configure explicit redirects/rewrites through a proxy, a Servlet/web filter, or even declare the additional route explicitly on the controller handler (like `@GetMapping("/some/greeting", "/some/greeting/")` for more targeted cases.

Until your application fully adapts to this change, you can change the default with the following global configuration:

[source, java]
----
@Configuration
public class WebConfiguration implements WebMvcConfigurer {

    @Override
    public void configurePathMatch(PathMatchConfigurer configurer) {
      configurer.setUseTrailingSlashMatch(true);
    }
  
}
----

- The report is defined in [`components/sbm-recipes-boot-upgrade/src/main/resources/recipes/27_30/report/sbu30-report.yaml`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/main/components/sbm-recipes-boot-upgrade/src/main/resources/recipes/27_30/report/sbu30-report.yaml)
- The (generated) test is defined in [`components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/report/helper/SpringMVCAndWebFluxURLMatchingChangesReportSectionTest`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/main/components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/report/helper/SpringMVCAndWebFluxURLMatchingChangesReportSectionTest.java)

**Comment by bsmahi** [comment]
Hi @fabapp2,

Many thanks for providing an opportunity.

I would like to contribute for this improvement of boot report changes, since am doing this for the first to spring, could you please guide me how/where to start, for the rest of the upgrade report I will pick it up myself.

In fact have signed contributor license agreement here https://cla.pivotal.io/sign/spring/icla#sign-form

Thanks,
Mahi

**Comment by fabapp2** [comment]
Thanks for your interest @bsmahi 🚀 
I am not very responsive at the moment.
I just realised this has been done with #529.
could you maybe pick another issue for a start?
