### ISSUE TITLE
3.0 Upgrade Report: Elasticsearch Clients and Templates

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#688]
labels: ["type: enhancement","good first issue","3.0.0","upgrade:boot-report","generated"]

## What needs to be done
The auto-generated section in the Spring Boot 3 Upgrade Report for the 'Elasticsearch Clients and Templates' section should be improved.

:warning: **Please read [Spring Boot 3 Upgrade Report Contribution Guideline](https://github.com/spring-projects-experimental/spring-boot-migrator/wiki/Spring-Boot-3-Upgrade-Report-Contribution-Guideline)** :warning:

[From the Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#elasticsearch-clients-and-templates)

> Support for Elasticsearch's high-level REST client has been removed.
In its place, auto-configuration for Elasticsearch's new Java client has been introduced.
Similarly, support for the Spring Data Elasticsearch templates that built on top of the high-level REST client has been removed.
In its place, auto-configuration for the new templates that build upon the new Java client has been introduced.
See the [Elasticsearch section of the reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/data.html#data.nosql.elasticsearch) for further details.

`ReactiveElasticsearchRestClientAutoConfiguration` has been renamed to `ReactiveElasticsearchClientAutoConfiguration` and has moved from `org.springframework.boot.autoconfigure.data.elasticsearch` to `org.springframework.boot.autoconfigure.elasticsearch`.
Any auto-configuration exclusions or ordering should be updated accordingly.

- The report is defined in [`components/sbm-recipes-boot-upgrade/src/main/resources/recipes/27_30/report/sbu30-report.yaml`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/main/components/sbm-recipes-boot-upgrade/src/main/resources/recipes/27_30/report/sbu30-report.yaml)
- The (generated) test is defined in [`components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/report/helper/ElasticsearchClientsAndTemplatesReportSectionTest`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/main/components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/report/helper/ElasticsearchClientsAndTemplatesReportSectionTest.java)

**Comment by krasowskiM** [comment]
Hello @fabapp2 I was thinking about contributing :) I could start with this issue. What is the general idea on the upgrade report improvement?

**Comment by fabapp2** [comment]
Hi @krasowskiM 

Happy you want to contribute 🚀 

This issue is about replacing the auto-generated section in the report with a more detailed description referencing matches found in the scanned application. Here usages of one of the classes affected by the package change.

I added a new section to the contribution guideline. Could you maybe read and provide feedback if this answers your questions and is helpful?
