### ISSUE TITLE
3.0 Migration: Elasticsearch Clients and Templates

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#689]
labels: ["type: enhancement","upgrade:boot-recipe","3.0.0","generated"]

## What needs to be done
Provide automated migration recipe(s) for mitigations of

- #688

where possible.

:warning: **Please read [Spring Boot 3 Upgrade Report Contribution Guideline](https://github.com/spring-projects-experimental/spring-boot-migrator/wiki/Spring-Boot-3-Upgrade-Report-Contribution-Guideline)** :warning:

**Comment by ravig-kant** [comment]
Hi @fabapp2 

I will like to pick up this enhancement.

**Comment by fabapp2** [comment]
Hi @ravig-kant !
Could you do #688 too (first)? I didn't look into it yet so the research would be on you too :)  
I am not very responsive but @sanagaraj-pivotal should be able to provide help.
