### ISSUE TITLE
spring-boot-upgrade does not use correct port when it asks to open the report

### ISSUE THREAD

**Issue by marcgemis** [spring-projects-experimental/spring-boot-migrator#693]
**Describe the bug**
When spring-boot-upgrade is started with a different port than 8080, it still asks to open the report on port 8080.

**To Reproduce**
1. run spring-boot-upgrade with e.g. java -Dsbm.gitSupportEnabled=false -Dserver.port=8432 --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED -jar spring-boot-upgrade.jar <your-project>
2. It executes and prints

 _____            _              ______             _     _____
/  ___|          (_)             | ___ \           | |   |____ |
\ `--. _ __  _ __ _ _ __   __ _  | |_/ / ___   ___ | |_      / /
 `--. \ '_ \| '__| | '_ \ / _` | | ___ \/ _ \ / _ \| __|     \ \
/\__/ / |_) | |  | | | | | (_| | | |_/ / (_) | (_) | |_  .___/ /
\____/| .__/|_|  |_|_| |_|\__, | \____/ \___/ \___/ \__| \____/
      | |                  __/ |
      |_|                 |___/
 _   _                           _       ______                      _
| | | |                         | |      | ___ \                    | |
| | | |_ __   __ _ _ __ __ _  __| | ___  | |_/ /___ _ __   ___  _ __| |_
| | | | '_ \ / _` | '__/ _` |/ _` |/ _ \ |    // _ \ '_ \ / _ \| '__| __|
| |_| | |_) | (_| | | | (_| | (_| |  __/ | |\ \  __/ |_) | (_) | |  | |_
 \___/| .__/ \__, |_|  \__,_|\__,_|\___| \_| \_\___| .__/ \___/|_|   \__|
      | |     __/ |                                | |
      |_|    |___/                                 |_|

powered by Spring Boot Migrator

-------------------------------------------------------------------------

Find us on GitHub:  https://via.vmw.com/8AD63p

Please report all errors:  https://via.vmw.com/bXlqJC

-------------------------------------------------------------------------

Scanning /Users/mgemis/Projects/p4/awp/bluecloud/microservices/eureka-server
finished scan. Please open: http://localhost:8080/spring-boot-upgrade

3. while it is listening on port 8432

**Expected behavior**
The text should read 
finished scan. Please open: http://localhost:8432/spring-boot-upgrade

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version  jar file provided via issue #601 on Jan 3, 2023.

**Comment by fabapp2** [comment]
Hi @marcgemis,
Valid point. Thanks for pointing this out. 🚀

**Comment by fabapp2** [comment]
@sanagaraj-pivotal do you want to look into this?

**Comment by sanagaraj-pivotal** [comment]
@fabapp2 I can look into this
