### ISSUE TITLE
Deprecate `ProjectContext.getBuildFile()`

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#695]
### What needs to be done
Deprecate `ProjectContext.getBuildFile()`

### Why it needs to be done
Using this method only works for single-module projects.
Deprecating the method and providing javadoc will communicate this to users.

**Comment by fabapp2** [comment]
@sanagaraj-pivotal ?

**Comment by sandeepnedeng** [comment]
Taking this.

**Comment by sanagaraj-pivotal** [comment]
Taking this
