### ISSUE TITLE
The recipe sql-access-in-java-ee-apps references a broken link

### ISSUE THREAD

**Issue by jstansel** [spring-projects-experimental/spring-boot-migrator#707]
**Describe the bug**
The recipe sql-access-in-java-ee-apps references a broken link

**SBM Version**
v0.13.0

**SBM Application**
 spring-boot-migrator

**To Reproduce**
https://appmod-cookbook.apps.pcfone.io/spring-bootify/sql/ referenced by recipe sql-access-in-java-ee-apps does not exist

**Expected behavior**
Provided reference should exist and be accessible

**Screenshots**
NA

**Stacktrace**
Refer to components/sbm-recipes-jee-to-boot/src/main/resources/recipes/javax.sql.yaml

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] NA
 - Version [e.g. 10] NA

**Additional context**

**Comment by fabapp2** [comment]
Thanks for reporting this @jstansel 🚀
