### ISSUE TITLE
how to disable sbm.gitSupportEnabled

### ISSUE THREAD

**Issue by keshavvarshney** [spring-projects-experimental/spring-boot-migrator#714]
Hi Team, 
 
I am using spring boot migrator tool and trying to run all my command from the java code by using the process builder to migrate my project to spring boot.

I need to disable sbm.gitSupportEnabled in my case. So I need to understand how can I do that ?

Regards,
KVarshney

**Comment by bsmahi** [comment]
Hi,

For windows users, you can use the following command

```java
set SBM_GITSUPPORTENABLED=false && java -jar spring-boot-migrator.jar
```

I hope that helps.

Thanks,
Mahi

**Comment by keshavvarshney** [comment]
Thanks Mahi.. It is working.

**Comment by keshavvarshney** [comment]
Thanks Mahi... It is working.

**Comment by sanagaraj-pivotal** [comment]
@keshavvarshney you can also try the below command as an alternative 
```
java -jar -Dsbm.gitSupportEnabled=false spring-boot-migrator.jar
```
