### ISSUE TITLE
Couldn't Download the JAR

### ISSUE THREAD

**Issue by RaghuManickam** [spring-projects-experimental/spring-boot-migrator#720]
Hi team ,

I am unable to download the Jar file . it throws 404 

https://github.com/spring-projects-experimental/spring-boot-migrator/releases/download/latest/spring-boot-upgrade.jar

**Comment by bsmahi** [comment]
Hi Raghu,

Latest release version is 0.13.0, you can download from the following link

https://github.com/spring-projects-experimental/spring-boot-migrator/releases/download/0.13.0/spring-boot-upgrade.jar

For more details, please refer to this link:
https://github.com/spring-projects-experimental/spring-boot-migrator/releases/tag/0.13.0

I am happy to assist you further.

Thanks,
Mahi

**Comment by fabapp2** [comment]
Thanks for reporting @RaghuManickam 🚀  
Thanks for helping @bsmahi 🚀 

I fixed the link in #732
