### ISSUE TITLE
Create a test helper to retrieve the latest version of a given dependency

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#731]
Create a test helper to retrieve the latest version of a given dependency

_Originally posted by @fabapp2 in https://github.com/spring-projects-experimental/spring-boot-migrator/issues/730#issuecomment-1445044201_

**Comment by fabapp2** [comment]
Can you pick this @sanagaraj-pivotal

**Comment by sanagaraj-pivotal** [comment]
Taking this

**Comment by fabapp2** [comment]
We decided to manually bump versions for now when required and ignore problematic tests for `UpgradeDependencyVersion` which is tested by OpenRewrite.
