### ISSUE TITLE
Kotlin support for Spring Boot 3 migrations

### ISSUE THREAD

**Issue by wleese** [spring-projects-experimental/spring-boot-migrator#733]
### What needs to be done

Recipes used to Spring Boot 3 migrations should support migration project written in Kotlin.
It would seem basic Kotlin support in openrewrite is on its way: https://github.com/openrewrite/rewrite-kotlin

### Why it needs to be done

Kotlin projects represent a large user base of Spring Boot.

### Acceptance Criteria

/info panel
**Given** A Spring Boot < 3.0 project written in Kotlin
**When** Running Spring Boot 3.0 upgrade recipes
**Then** Kotlin classes receive the same treatment as Java classes

**Comment by fabapp2** [comment]
Thanks for your interest in Kotlin support. 
This topic came up in the past, also see #448 
We currently have no resources to look into it, but we know that Rewrite is working on Kotlin support.
