### ISSUE TITLE
http://localhost:8080/spring-boot-upgrade cannot be opened

### ISSUE THREAD

**Issue by xiaowu2012** [spring-projects-experimental/spring-boot-migrator#735]
**Describe the bug**

powered by Spring Boot Migrator

-------------------------------------------------------------------------

Find us on GitHub:  https://via.vmw.com/8AD63p

Please report all errors:  https://via.vmw.com/bXlqJC

-------------------------------------------------------------------------

Scanning xxxx
**finished scan. Please open: http://localhost:8080/spring-boot-upgrade**

**SBM Version**
0.13.0

**SBM Application**
jar

**To Reproduce**
1. Run java -jar -Dlogging.config=/Users/xx/IdeaProjects/jakarta/spring-boot-migrator/components/sbm-core/src/main/resources/logback-spring.xml --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED spring-boot-upgrade.jar /Users/xx/IdeaProjects/viruscanning/xxxx

**Expected behavior**
Follow the guidance I can open the localhost:8080

**Screenshots**

**Stacktrace**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 13.2.1 (22D68)

**Additional context**

**Comment by sanagaraj-pivotal** [comment]
@xiaowu2012 is this behaviour found in release version 0.13.0 or the latest compiled jar ?

**Comment by sanagaraj-pivotal** [comment]
@xiaowu2012 We will release new version shortly, possibly this error might not be carried over.
