### ISSUE TITLE
Error: SBM requires a Maven build file. Please provide a minimal pom.xml.

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects-experimental/spring-boot-migrator#753]
**Describe the bug**

Spring Boot migrator fails to scan source directory

**SBM Version**

0.13.0

**SBM Application**
spring-boot-migrator

**To Reproduce**
1. We ran the migrator outside of the source folder and then type "scan c:\\sources\\". Here's the output:

```
scanning 'C:\sources\'

Checked preconditions for 'C:\sources\'
 [X] SBM requires a Maven build file. Please provide a minimal pom.xml.
[ok] 'sbm.gitSupportEnabled' is 'true', changes will be committed to branch [master] after each recipe.
 [!] Java 11 or 17 is required. Check found Java 20.
 [X] PreconditionCheck check could not find a 'src/main/java' dir. This dir is required.
```

If we put migrator tool in the source folder, run it and type "scan ." then scan process is working as expected.

**Expected behavior**
Spring Boot Migrator should scan the source folder.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by bsmahi** [comment]
Hi @sergey-morenets 
In my understanding, scan will work inside migrator. Because, we'll run the migrator jar and then we will execute `scan <path-of-the-application>`
https://github.com/spring-projects-experimental/spring-boot-migrator#spring-boot-30-migrator---java-cli

I am happy to assist you further.

Thanks,
Mahi

**Comment by sergey-morenets** [comment]
Hi @bsmahi 

Let me clarify my steps. Can I do the following?

1) Put migrator jar into c:\Temp folder
2) Run migrator and type "scan c:\sources\'' 

Source project is in the c:\sources folder.

**Comment by bsmahi** [comment]
Hi @sergey-morenets 

Does your path of the application contains any Pom.xml?

If not, we should have pom.xml in the source application for further scanning.

I hope that helps, am happy to assist you further.

Thanks,
Mahi

**Comment by sergey-morenets** [comment]
@bsmahi 

Yes, it contains pom.xml. I wrote in the original post that if I put migrator jar into the source folder and type "scan ." then scanning works correctly.

**Comment by bsmahi** [comment]
@sergey-morenets 

Is it possible to zip it sources which you're checking. Will verify it.

Have followed the same steps as yours by taking out simple-jms(which was in side/spring-boot-migrator-main/testcode) and placed it in C:/

1. Ran spring Boot migrator
2. Executed scan C:\\simple-jms

![image](https://user-images.githubusercontent.com/5474948/228206610-4f01b1f5-7e6b-41e4-a799-84269fb070a6.jpeg)

Thanks,
Mahi

**Comment by fabapp2** [comment]
Hi @bsmahi thank you very much for assisting during my leave!
If I understood correct than the problem ghas been solved?
@sergey-morenets I will close the issue now. If the problem persists feel free to reopen again.
