### ISSUE TITLE
Fix User documentation

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#776]
### What needs to be done
Some links point to non-existent sections. 
Either remove the links or add the missing sections.

**Comment by bsmahi** [comment]
Hi @fabapp2 

Please let me know which README documentation I need to correct those.

I would like to fix this.

Thanks,
Mahi

**Comment by fabapp2** [comment]
Hi @bsmahi
thanks for your interest!
This references the user documentation under docs/reference/user-documentation.adoc.
The links point to internal resources. You could comment out the sections with a todo for now.

**Comment by bsmahi** [comment]
Hi @fabapp2,

Have done the as per the above instructions, could you please review it, here go with the PR
https://github.com/spring-projects-experimental/spring-boot-migrator/pull/802

Thank you,
Mahi
