### ISSUE TITLE
Move logic from `RewriteRecipeRunner` into `ProjectContext.apply(Recipe)`

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#803]
### What needs to be done
The logic from `RewriteRecipeRunner.run(ProjectContext, Recipe)` should be moved into `ProjectContext.apply(Recipe)` following the same concept as in other classes (e.g. OpenRewriteMavenBuildFile or OpenRewriteJavaSource).

### Why it needs to be done
To use the same concept everywhere

**Comment by sourav15102** [comment]
Hi team,

I want to work on this issue.
I will refer to https://github.com/spring-projects-experimental/spring-boot-migrator/wiki/Spring-Boot-3-Upgrade-Report-Contribution-Guideline for contribution guidelines.

-Sourav

**Comment by fabapp2** [comment]
Thanks for your PR @sourav15102.
