### ISSUE TITLE
SBM tool -  migrate-stateless-ejb isssue

### ISSUE THREAD

**Issue by brebDevv** [spring-projects-experimental/spring-boot-migrator#837]
**Describe the bug**
Running the migrate-stateless-ejb from the terminal in Windows/Linux, is making SBM to throw this error:
ERROR o.s.sbm.java.impl.OpenRewriteMember - Could not get Type for annotation: 'EJB' while comparing with 'javax.inject.Inject'.

**SBM Version**
0.11 and 0.11.1 , since the application is using Java 11 and not Java 17

**SBM Application**
Shell

**To Reproduce**
1. Run SBM shell.
2. Run scan on the project
3. Run: apply migrate-stateless-ejb
4. See error that looks like: ERROR o.s.sbm.java.impl.OpenRewriteMember - Could not get Type for annotation: 'EJB' while comparing with 'javax.inject.Inject'.

**Expected behavior**
I've would expect for all the @EJB to be migrated to @Autowired 

**Screenshots**
![sbm_error](https://github.com/spring-projects-experimental/spring-boot-migrator/assets/17686627/16255e7b-444b-4a19-abf6-420b81b10773)

**Stacktrace**
There isn't any stacktrace, except the  error that appears in the terminal:
ERROR o.s.sbm.java.impl.OpenRewriteMember - Could not get Type for annotation: 'EJB' while comparing with 'javax.inject.Inject'.

**Comment by fabapp2** [comment]
Thanks for reporting and giving SBM a try @brebDevv 🚀 

What I learn from your issue is that SBM should allow using JDK versions supported by OpenRewrite and not force you to an outdated version. I will create a new issue for this.
I assume it's not easy for you to switch to JDK 17 and use a recent version of SBM, or?

**Comment by brebDevv** [comment]
HI @fabapp2 . Unfortunately it's not easy to upgrade to JDK17. That's why I've tried with SBM versions: 0.11 and 0.11.1 , since I've seen that from 0.12 -> 0.14 it requires only the JDK 17.

**Comment by fabapp2** [comment]
Hi @brebDevv 
please excuse my delayed reply. 
This error indicates that the type for `Inject` could not be resolved.
You could check if the dependency is there and if it's broken. 
Or just delete the dir under `~/.m2/reposuitory/javax/inject/...` and `~/.rewrite/cache` and see if the dependency gets downloaded. The recipe should then run.
I'll close this issue for now. Please reopen if the error persists.
