### ISSUE TITLE
Adhere to `~/.m2/settings-security.xml` and `~/.m2/settings.xml`

### ISSUE THREAD

**Issue by fabapp2** [spring-projects-experimental/spring-boot-migrator#880]
The new `sbm-support-rewrite` component should enrich `ExecutionContext` with information from `~/.m2/settings.xml` and use (encrypted) passwords from `security-settings.xml` for auth.

This was started in branch [771](https://github.com/spring-projects-experimental/spring-boot-migrator/tree/771-upgrade-to-latest-openrewrite-7402) and the required logic needs to be moved and integrated into `sbm-support-rewrite` component and put to use in `RewriteProjectParser`. 

The 771 branch contains a test for `security-settings.xml`. This test should be run with both parsers in `sbm-support-rewrite`.
`RewriteMavenParser` uses all code from the `rewrite-maven-plugin` and should act as reference. The `RewriteProjectParser` should produce the exact same result and will in the future replace the RewriteMavenParser.

These are the tests for the logic that needs to be moved:
- [`RewriteMavenSettingsInitialierTest`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/c7be9a2573dd7577924d008668e6185d90ff633b/components/sbm-core/src/test/java/org/springframework/sbm/project/parser/RewriteMavenSettingsInitialierTest.java)
- [`MavenPasswordDecrypterTest`](https://github.com/spring-projects-experimental/spring-boot-migrator/blob/c7be9a2573dd7577924d008668e6185d90ff633b/components/sbm-core/src/test/java/org/springframework/sbm/project/parser/MavenPasswordDecrypterTest.java)

**Comment by bsmahi** [comment]
@fabapp2 as discussed could you please assign this to me?

Thanks,
Mahi

**Comment by shresthaujjwal** [comment]
@bsmahi @fabapp2 any update or progress on this ?

**Comment by fabapp2** [comment]
Closed by #986
